# 压缩格式存储

In [5]:
import numpy as np
from scipy.sparse import coo_matrix,csr_matrix,csc_matrix

indptr = np.array([0,2,3,6])
indices = np.array([0,2,2,0,1,2])
data = np.array([1,2,3,4,5,6])
csr_matrix((data,indices,indptr),shape=(3,3)).toarray()


array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [14]:
indptr = np.array([0,2,3,6])
indices = np.array([0,2,2,0,1,2])
data = np.array([1,2,3,4,5,6])
csc_matrix((data,indices,indptr),shape=(3,3)).toarray()

array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]])

In [15]:
indptr = np.array([0,4,4,6,9,15,19])
indices = np.array([1,2,3,5,0,5,1,3,5,0,1,2,3,4,5,1,2,3,5])
data = np.array([1,3,5,7,1,2,1,2,3,1,1,1,1,1,1,3,4,2,1])
csc_matrix((data,indices,indptr),shape=(6,6)).toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 3],
       [3, 0, 0, 0, 1, 4],
       [5, 0, 0, 2, 1, 2],
       [0, 0, 0, 0, 1, 0],
       [7, 0, 2, 3, 1, 1]])

In [11]:
indptr = np.array([0,2,3,6])
indices = np.array([0,2,1,2,0,1,2])
data = np.array([1,2,1,3,4,5,6])
csc_matrix((data,indices,indptr),shape=(3,3)).toarray()

array([[1, 0, 4],
       [0, 1, 5],
       [2, 0, 3]])

In [12]:
indptr = np.array([0,2,3,6])
indices = np.array([0,1,2,2,0,1,2])
data = np.array([1,1,2,3,4,5,6])
csc_matrix((data,indices,indptr),shape=(3,3)).toarray()

array([[1, 0, 4],
       [1, 0, 5],
       [0, 2, 3]])

In [8]:
from numpy import array
from scipy.sparse import coo_matrix
row = array([0,0,1,3,1,0,0])
col = array([0,2,1,3,1,0,0])
data = array([2,1,3,1,2,1,4])
A = coo_matrix((data,(row,col)),shape=(4,4))
print("--------coo_matrix--------")
print(A)

print()
print("--------toarray---------")
print(A.toarray())

B = A.tocsc()
print()
print("--------toscs---------")
print(B)

C = B.todense()
print()
print("--------todense---------")
print(C)

--------coo_matrix--------
  (0, 0)	2
  (0, 2)	1
  (1, 1)	3
  (3, 3)	1
  (1, 1)	2
  (0, 0)	1
  (0, 0)	4

--------toarray---------
[[7 0 1 0]
 [0 5 0 0]
 [0 0 0 0]
 [0 0 0 1]]

--------toscs---------
  (0, 0)	7
  (1, 1)	5
  (0, 2)	1
  (3, 3)	1

--------todense---------
[[7 0 1 0]
 [0 5 0 0]
 [0 0 0 0]
 [0 0 0 1]]


In [3]:
import numpy as np
# 读取vel.csv
with open('./data/pemsd7-m/vel.csv',encoding='utf-8') as f:
    data_2 = np.loadtxt(f,delimiter=',')
    print(data_2.shape)

(12672, 228)


In [4]:
import scipy.sparse as sp
data = sp.load_npz('./data/pemsd7-m/adj.npz')
print(data)

  (0, 0)	1.0
  (1, 0)	0.874723658573536
  (2, 0)	0.3612846282098772
  (3, 0)	0.150751115862349
  (4, 0)	0.44773753416261347
  (7, 0)	0.9366682108438592
  (8, 0)	0.6294460508233404
  (11, 0)	0.7839333057097398
  (12, 0)	0.3309976422216514
  (15, 0)	0.6802770768089623
  (58, 0)	0.10052330878754748
  (65, 0)	0.10478651398778062
  (68, 0)	0.12590298087652654
  (108, 0)	0.5608901322885123
  (109, 0)	0.6899634477684644
  (112, 0)	0.20452601018760724
  (114, 0)	0.32572485193348727
  (115, 0)	0.8756092297080661
  (116, 0)	0.1010639188922501
  (118, 0)	0.30866295600959187
  (120, 0)	0.7924221612667589
  (123, 0)	0.9318102066961166
  (124, 0)	0.4643323538620246
  (126, 0)	0.5328487422206488
  (127, 0)	0.8412964212185728
  :	:
  (185, 227)	0.406905517928299
  (186, 227)	0.15049343836804044
  (187, 227)	0.18220630019898112
  (188, 227)	0.3979505510953252
  (192, 227)	0.17455919974749026
  (193, 227)	0.4049386337428703
  (195, 227)	0.13101336046275158
  (197, 227)	0.13362495666231547
  (203, 227)	0